// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDU0g3DpBg2go8VTqXj0SPwKgnaL4FHzQg',
    appId: '1:578162788399:web:6d0708a717d58a43eededa',
    messagingSenderId: '578162788399',
    projectId: 'logindesign-64914',
    authDomain: 'logindesign-64914.firebaseapp.com',
    storageBucket: 'logindesign-64914.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4pbcaRnphPWrKMTQxWJeZmU5Kv9N5x7A',
    appId: '1:578162788399:android:87a707f6050e3c78eededa',
    messagingSenderId: '578162788399',
    projectId: 'logindesign-64914',
    storageBucket: 'logindesign-64914.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpjPwMl8N42bFcEIsRx-T_XAVIuRuCFuY',
    appId: '1:578162788399:ios:58df8768744545e7eededa',
    messagingSenderId: '578162788399',
    projectId: 'logindesign-64914',
    storageBucket: 'logindesign-64914.appspot.com',
    iosBundleId: 'com.example.logindesign',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpjPwMl8N42bFcEIsRx-T_XAVIuRuCFuY',
    appId: '1:578162788399:ios:51ccb15516af8916eededa',
    messagingSenderId: '578162788399',
    projectId: 'logindesign-64914',
    storageBucket: 'logindesign-64914.appspot.com',
    iosBundleId: 'com.example.logindesign.RunnerTests',
  );
}
